### PR TITLE
Added information for installing the correct version of `ocamlformat`

### PR DESCRIPTION
**Pull request by IIITM-Jay**
## Description
This is in continuation with #22. This PR describes how to install the correct version of `ocamlformat` with a bit information to help new contributors.

## Changes Incorporated
The following changes has been made to the `CONTRIBUTING.md` file:

- [x] Information has been added on how to install the correct version of `ocamlformat`
- [x] Added a Link to github page of `ocamlformat`

### CODE REVIEW

**Comment by IIITM-Jay** [comment]
Hi Sir, @patricoferris , May I request you to have a look on this PR. 
Waiting for your valuable feedback on the same :pray:

**Review by patricoferris — CHANGES_REQUESTED** [review]
Thanks @IIITM-Jay :))

I've tried to make your explanation a little more concise. I really appreciate the welcoming tone, but it also got a little bit wordy I think which was confusing.

**Comment by IIITM-Jay** [comment]
Hi @patricoferris Sir, Thank you so much for reviewing!
I have committed the suggestions and the changes that you have been asked.

Sir, all the suggestive changes have been incorporated now.

**Comment by patricoferris** [comment]
Thanks ! :))

**Pull request merged**
