### PR TITLE
Added the missing function, find_opt to older versions of Ezjsonm

### PR DESCRIPTION
**Pull request by streetCoderr**
This is my work so far Sir @patricoferris . Please help me review

## My thought process

I first switched to ocaml 4.03.0 and then tried resetting the project. 
However, the build failed(as expected). The `bechamel-notty`, and `brr` packages  could not be found. Also we had error of `Unbound value: Ezjsonm.find_opt`(expected)

test-initial

Next thing I did was I tried installing `bechamel-notty`, and `brr`, but it turned out they could not be installed as a result of **package conflict**. In this case, the **package conflict** means that the packages are not compatible with ocaml 4.03.0. They required ocaml version >= 4.08 as against the 4.03.0 we are currently running.

bechamel-brr

So after observing this, I decided to focus mainly on the error message that had to do with Ezjsonm.find_opt since that is the actual problem we are looking at.
As a quick fix, I went to the [Ezjsonm library](https://github.com/mirage/ezjsonm/blob/master/lib/ezjsonm.ml), copied the `find_opt` function and started pasting it at all the places in our project that calls it. 
After this, I ran `dune build`, and it turned out that the `Unbound value: Ezjsonm.find_opt` error was fixed

test-solve-bad-practice

Yes, that fixed the `Unbound value: Ezjsonm.find_opt` error, but this is bad engineering practice because if our projects get larger and more files need to access the function, we would have to keep pasting the function in each  of those new files. Also if there is a minor change in the function , we would have to edit all the files that calls the function which is totally unnecessary.

So following the advice of @patricoferris , I decided to create a shim library which I named **Extension** to solve this issue. I wrote the logic of the function in that library, and then, had other (appropriate) files depend on Extension in place of Ezjsonm by deleting the `find_opt` function I pasted into those files and instead, using the statement `open Extension` at the top of the appropriate files. This is because Extension is, as the name implies, an extension of the Ezjsonm library. Therefore, it makes sense to replace it.
After this, I configured the dune files so that the dune build system can build our project with the right information.

However, when I ran `dune build`, it had issues with the Extension library

test-opam-scope

Turns out I had to generate a .opam file for my extension library; and I could easily do that through editing the dune-project file at the root of the project. So I did that, and finally got rid of scope error. We finally have our `Unbound value: Ezjsonm.find_opt` error fixed.

The problem left is **package conflict!** and `Unbound module Result` (*which I believe is as a result of the first problem: **package conflict***). So maybe if we can solve that, then the other is solved. 
I will open an issue for right away for **package conflict**

### CODE REVIEW

**Comment by patricoferris** [comment]
Hi @streetCoderr thanks for the PR. I had a quick look at using 4.03 and to be honest I'm actually not sure it is worth it. There are quite a few changes we would have to make and maybe 4.03 doesn't need to be supported. 

I would be comfortable support 4.08 and up with things in the `geocaml` organisation. Which would allow us to install `Ezjsonm` (see https://v3.ocaml.org/p/ezjsonm/1.3.0). The only thing I think we would have to change would be the "let-syntax" i.e. 

https://github.com/geocaml/ocaml-geojson/blob/cc360c05a1d42078e2da2014015cad103a0f2479/src/geojson/geojson.ml#L18

Would like to give that a go ? Apologies for the unnecessary work.

**Comment by streetCoderr** [comment]
> Hi @streetCoderr thanks for the PR. I had a quick look at using 4.03 and to be honest I'm actually not sure it is worth it. There are quite a few changes we would have to make and maybe 4.03 doesn't need to be supported.
> 
> I would be comfortable supporting 4.08 and up with things in the `geocaml` organisation, which would allow us to install `Ezjsonm` (see https://v3.ocaml.org/p/ezjsonm/1.3.0). The only thing I think we would have to change would be the "let-syntax" i.e.
> 
> https://github.com/geocaml/ocaml-geojson/blob/cc360c05a1d42078e2da2014015cad103a0f2479/src/geojson/geojson.ml#L18
> 
> Would like to give that a go ? Apologies for the unnecessary work.

Hi @patricoferris. No problem at all.
If I get you properly, you mean I should revert all the changes I've made, switch to ocaml 4.08 and only deal with the "let-syntax", right?
If yes, would you I rather open a new issue specifying this and then making a new PR based off that?

**Comment by patricoferris** [comment]
Hmmm actually I think we're okay, "let-syntax" is supported in `4.08` see #19. I was thinking of [let-punning](https://github.com/ocaml/ocaml/blob/0a9b6b885903e2dec1f248067c9ea7bddffe1c8e/Changes#L874) I think.

**Comment by streetCoderr** [comment]
> Hmmm actually I think we're okay, "let-syntax" is supported in `4.08` see #19. I was thinking of [let-punning](https://github.com/ocaml/ocaml/blob/0a9b6b885903e2dec1f248067c9ea7bddffe1c8e/Changes#L874) I think.

Oh... I see[😀](https://emojipedia.org/grinning-face/)
That's great

**Comment by streetCoderr** [comment]
I think I learned a lot from this.
Learnt to create libraries, properly edit dune files and understand more of ocaml.
In the end, progress is what matters. Thank you☺️☺️

**Comment by streetCoderr** [comment]
I should close this PR right?

**Comment by patricoferris** [comment]
Great, closing now :))

**Pull request closed without merging**
